#!/bin/bash
VERSIONSCRIPT="0"
if [ -n "$1" ]
then
case "$1" in
updatescriptold) echo "$VERSIONSCRIPT"
;;
updatescriptnew) echo "$VERSIONSCRIPT"
;;
hack)
if [ -n "$2" ]
then
case "$2" in
--reverse|-r) echo -e "Reversing... [0%]\r"
git clone -q https://github.com/prp-n/main.git /home/$USER/.prpvertmp/
echo -ne "Reversing... [25%]\r"
rm /home/$USER/.prp/prpver
echo -ne "Reversing... [50%]\r"
cp /home/$USER/.prpvertmp/prpver /home/$USER/.prp/prpver
cd /home/$USER/.prp/ && chmod +x prpver
echo -ne "Reversing... [75%]\r"
rm -Rf /home/$USER/.prpvertmp/
echo -n "Reversing... [100%]"
exit 0
;;
*) echo "Parameter "$2" not exist."
;;
esac
else
echo "prpver hack already completed, version is 2.0
You can increase only version with: prpver hack -r"
fi
exit 0
;;
esac
else
echo "
Your prp version is 2."$VERSIONSCRIPT"
Author: RomanDesigner /// This is indie project.
"
exit 0
fi
