#!/bin/bash
VERSIONSCRIPT="0"
if [ -n "$1" ]
then
case "$1" in
updatescriptold) echo "$VERSIONSCRIPT"
;;
updatescriptnew) echo "$VERSIONSCRIPT"
;;
hack) echo "prpver hack already completed, version is 2.0"
exit 0
;;
esac
else
echo "
Your prp version is 2."$VERSIONSCRIPT"
Author: RomanDesigner /// This is indie project.
"
exit 0
fi
